### ISSUE TITLE
publish near-memory-tracker on cargo.io

### ISSUE THREAD

**Issue by pmnoxx** [near/near-memory-tracker#6]
- [x] update license to apache
- [x] Fix cargo.toml for crates.it
- [x] Run `cargo publish —dry-runs
- [x] Fix warnings
- [x] Publish
- [x] Check how crates.io page looks like / make adjustments 
- [x] Add near organization to owners  (added nearmax for now)
$ cargo owner --add nearmax

**Comment by pmnoxx** [comment]
https://github.com/near/nearcore/issues/3889

**Comment by pmnoxx** [comment]
Added to https://crates.io/crates/near-rust-allocator-proxy

**Comment by pmnoxx** [comment]
@bowenwang1996 who should I add as owner?
